spring.application.name=auth
spring.datasource.url=jdbc:postgresql://localhost:5432/auth_db
spring.datasource.username=user
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update

jwt.secret=${JWT_SECRET}
jwt.expiration=3600000
